### ISSUE TITLE
[Invalid]: Sass Deprecation Legacy API

### ISSUE THREAD

**Issue by onissen** [ncs-northware/northware#123]
### Beschreibe das Problem

Next.js 15.0.2 nutzt noch die "legacy JS API" aus Sass, um die Stylesheets zu compilen. Diese API ist deprecated und wird in `sass@2.x` entfernt. Dieses Problem muss von Next.js behoben werden.

### Weitere Beschreibungen

- [Sass Artikel Deprecation Legacy API](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/)
- [Next.js Issue zu dem Thema](https://github.com/vercel/next.js/issues/71638)
- [Next.js Discussion dazu](https://github.com/vercel/next.js/discussions/67931)
- [Next.js Pull Request der das lösen könnte](https://github.com/vercel/next.js/pull/72202)

**Comment by Eigilak** [comment]
Btte auf English :D
